### PR TITLE
Tests alignment after removal of mender-auth-azure-iot from component

### PR DESCRIPTION
**Pull request by merlin-northern**
ChangeLog:title
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Comment by merlin-northern** [comment]
@oleorhagen I honestly do not know if that is regression somewhere else, or if the tests should be fixed. for now I need this one in, for the tests to pass in master.

**Review by oleorhagen — APPROVED** [review]
Pre-approving. But could you just add in the commit header that it's related to removing `auth-azure` ? :pray:

**Comment by merlin-northern** [comment]
> Pre-approving. But could you just add in the commit header that it's related to removing `auth-azure` ? 🙏

of course Sir, thank you Sir for the review, Sir. https://github.com/mendersoftware/integration-test-runner/compare/80ed1f8ec30c6f83bfec0f371c815166ac2111ee..d63933dfc2b16c2c19b8448d836d8c6f35312b84

**Comment by oleorhagen** [comment]
> of course Sir, thank you Sir for the review, Sir. https://github.com/mendersoftware/integration-test-runner/compare/80ed1f8ec30c6f83bfec0f371c815166ac2111ee..d63933dfc2b16c2c19b8448d836d8c6f35312b84

I'm blue blooded today, apparently :crown:  :sunglasses:

**Pull request merged**
