### PR TITLE
feat: Also comment on cherry-picking to the latest released version

### PR DESCRIPTION
**Pull request by oleorhagen**
We don't always know if the latest version will need support in the future or
not, so we really have to cherry-pick to it, just in case.

Ticket: QA-496
Changelog: None

Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

### CODE REVIEW

**Comment by oleorhagen** [comment]
Won't pass CI in some of the old tests due to the changes, which brings up the question of the integration version used in unit tests...

I know we've been over this before, but hardcoding it could be an option for our tests to get a known version.. But then again, has some weaknesses too. 

What are your thoughts on the topic these days @lluiscampos ?

**Comment by oleorhagen** [comment]
I know the inline testdata is gigantic. You want it split out in a separate file?

**Comment by oleorhagen** [comment]
@lluiscampos more to your liking?

**Review by lluiscampos — APPROVED** [review]
Looks good! :rocket:

**Pull request merged**
